# Generated by Django 3.1.3 on 2021-01-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('condition', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('shipping_cost', models.CharField(max_length=200)),
                ('picture_1', models.CharField(max_length=200)),
                ('picture_2', models.CharField(max_length=200)),
                ('picture_3', models.CharField(max_length=200)),
                ('picture_4', models.CharField(max_length=200)),
            ],
        ),
    ]
