# Generated by Django 3.1.3 on 2021-01-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freemarket', '0003_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='number',
            new_name='title',
        ),
    ]
