# Generated by Django 3.1.3 on 2021-01-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemarket', '0004_auto_20210105_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='icon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='line',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='mail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='twitter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
