# Generated by Django 3.1.3 on 2021-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freemarket', '0007_auto_20210108_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loginuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('mail', models.CharField(max_length=200, null=True)),
                ('line', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='icon',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='line',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
